### Credits:

<img align="left" src="https://ithaka-labs.s3.amazonaws.com/static-files/images/tdm/tdmdocs/CC_BY.png"><br />

This notebook is created by Zhuo Chen based on the notebooks created by [Nathan Kelber](http://nkelber.com), [William Mattingly](https://github.com/wjbmattingly/tap-2022-pandas) and [Melanie Walsh](https://github.com/melaniewalsh/Data-Analysis-with-Pandas) under [Creative Commons CC BY License](https://creativecommons.org/licenses/by/4.0/).<br />
For questions/comments/improvements, email zhuo.chen@ithaka.org or nathan.kelber@ithaka.org<br />

Reused and modified for internal use at Università Cattolica del Sacro Cuore di Milano, by Deborah Grbac, email deborah.grbac@unicatt.it and Valentina Schiariti, email valentina.schiariti-collaboratore@unicatt.it, released under CC BY License.

This repository is founded on **Constellate notebooks**. The original Jupyter notebooks repository was designed by the educators at **ITHAKA's Constellate project**. The project was sunset on July 1, 2025. This current repository uses and resuses Constellate notebooks as Open Educational Resources (OER), free for re-use under a Creative Commons CC BY License.
___

# Pandas Basics 1

**Description:** This notebook describes how to:
* Create a Pandas Series or a DataFrame
* Create a dataframe from files of different formats
* Explore the data in a dataframe
* Access data from a dataframe
* Set values in a dataframe
* Create a new column based on an existing one

This is the first notebook in a series on learning to use Pandas. 
___

## Introduction

Pandas is a Python library that allows you to easily work with tabular data. Most people are familiar with commercial spreadsheet software, such as Microsoft Excel or Google Sheets. While spreadsheet software and Pandas can accomplish similar tasks, each has significant advantages depending on the use-case.

**Advantages of Spreadsheet Software**
* Point and click
* Easier to learn
* Great for small datasets (<10,000 rows)
* Better for browsing data

**Advantages of Pandas**
* More powerful data manipulation with Python
* Can work with large datasets (millions of rows)
* Faster for complicated manipulations
* Better for cleaning and/or pre-processing data
* Can automate workflows in a larger data pipeline

In short, spreadsheet software is better for browsing small datasets and making moderate adjustments. Pandas is better for automating data cleaning processes that require large or complex data manipulation.

In [30]:
# import pandas, `as pd` allows us to shorten typing `pandas` to `pd` when we call pandas
import pandas as pd

## Pandas Series and Pandas DataFrame
In Pandas, data are stored in two fundamental objects: 

* **Pandas Series** - a single column or row of data
* **Pandas DataFrame** - a table of data containing multiple columns and rows

### Pandas Series

We can think of a Series as a single column or row of data. Here we have a column called `Champions` with the country names of the winners of the most recent ten FIFA world cup games.

|Champions|
|---|
|Argentina|
|France|
|Germany|
|Spain|
|Italy|
|Brazil|
|France|
|Brazil|
|Germany|
|Argentina|

Let's create a Series based on this column. To create our Series, we pass a **list** into the `.Series()` method:

In [31]:
# Create a data series object in Pandas
champions = pd.Series(["Argentina",
                       "France", 
                       "Germany", 
                       "Spain", 
                       "Italy", 
                       "Brazil", 
                       "France", 
                       "Brazil", 
                       "Germany",
                       "Argentina"]
                    )
champions

0    Argentina
1       France
2      Germany
3        Spain
4        Italy
5       Brazil
6       France
7       Brazil
8      Germany
9    Argentina
dtype: object

In [32]:
numbers = pd.Series([1,2,3,4,5,6])
numbers

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

As you can see, in addition to the data column, we also have an index column. By default, the indexes are numbers starting from 0. We could define the indexes ourselves. To do that, we will pass a **dictionary** to the `.Series()` method. The keys of the dictionary will be used as indexes.

In [33]:
# Use self-defined indexes
pd.Series({2022: "Argentina", 
           2018: "France", 
           2014: "Germany", 
           2010: "Spain", 
           2006: "Italy", 
           2002: "Brazil", 
           1998: "France", 
           1994: "Brazil", 
           1990: "Germany",
           1986: "Argentina"}
         )

2022    Argentina
2018       France
2014      Germany
2010        Spain
2006        Italy
2002       Brazil
1998       France
1994       Brazil
1990      Germany
1986    Argentina
dtype: object

You can give a name to your Pandas Series using the `name` parameter.

In [34]:
# give a name to the series
pd.Series({2022: "Argentina", 
           2018: "France", 
           2014: "Germany", 
           2010: "Spain", 
           2006: "Italy", 
           2002: "Brazil", 
           1998: "France", 
           1994: "Brazil", 
           1990: "Germany",
           1986: "Argentina"}, 
          name = 'World Cup Champions'
         )

2022    Argentina
2018       France
2014      Germany
2010        Spain
2006        Italy
2002       Brazil
1998       France
1994       Brazil
1990      Germany
1986    Argentina
Name: World Cup Champions, dtype: object

### Pandas DataFrame

While a Pandas Series is 1-dimensional with a single column/row of data, a Pandas DataFrame is 2-dimensional and can have multiple columns and rows. 

|Year|Champion|Host|
|---|---|---|
|2022|Argentina|Qatar|
|2018|France|Russia|
|2014|Germany|Brazil|
|2010|Spain|South Africa|
|2006|Italy|Germany|
|2002|Brazil|Korea/Japan|
|1998|France|France|
|1994|Brazil|USA|
|1990|Germany|Italy|
|1986|Argentina|Mexico|

Let's create a Pandas DataFrame based on this table. To create our dataframe, we pass a **dictionary** into the `DataFrame()` method. Each `key:value` pair will form a column in the dataframe, with the key as the column name and the value as the data in that column.

In [35]:
# Create a Pandas dataframe
wcup = pd.DataFrame({"Year": [2022, 
                              2018, 
                              2014, 
                              2010, 
                              2006, 
                              2002, 
                              1998, 
                              1994, 
                              1990,
                              1986], 
                     "Champion": ["Argentina", 
                                  "France", 
                                  "Germany", 
                                  "Spain", 
                                  "Italy", 
                                  "Brazil", 
                                  "France", 
                                  "Brazil", 
                                  "Germany", 
                                  "Argentina"], 
                     "Host": ["Qatar", 
                              "Russia", 
                              "Brazil", 
                              "South Africa", 
                              "Germany", 
                              "Korea/Japan", 
                              "France", 
                              "USA", 
                              "Italy", 
                              "Mexico"]
                    })

wcup

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany
5  2002     Brazil   Korea/Japan
6  1998     France        France
7  1994     Brazil           USA
8  1990    Germany         Italy
9  1986  Argentina        Mexico

In a Pandas dataframe, each row/column is technically a Pandas Series. We can see this by selecting the first row with the `iloc` method and check its type.

In [36]:
# Get the type of a row in a dataframe
type(wcup.iloc[0])

pandas.core.series.Series

Let's select a column and check its type.

In [37]:
# Get the type of a column in a dataframe
type(wcup['Champion'])

pandas.core.series.Series

We will describe row/column selection in greater detail below.

## Read and write tabular data in Pandas

Pandas provides different methods to read and write tabular data. The methods used to read in data from files are `.read_*()`. The methods used to write data into files are `.to_*()`.

Pandas can read data from files of many different formats and write data into files of many different formats. 
<center><img src="./data/Pandas1_DiffFormats.png" width="700"></center>

In [45]:
### Create the data folder
from pathlib import Path

# Check if a data folder exists. If not, create it.
data_folder = Path('./data/')
data_folder.mkdir(exist_ok=True)

|Method|Reveals|
|---|---|
|pd.read_csv( )| Creating a DataFrame from a CSV file |
|pd.read_excel( )| Creating a DataFrame from an Excel file|
|pd.read_json( )|Creating a DataFrame from a JSON file|

For example, we can **create a dataframe from a csv file** using the `.read_csv()` method.

In [46]:
# Use the read_csv() method to create a dataframe
failed_banks = pd.read_csv('./data/Pandas1_failed_banks_since_2000.csv')
failed_banks.head(5)

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund
0,First Republic Bank,San Francisco,CA,59017,"JPMorgan Chase Bank, N.A.",1-May-23,10543
1,Signature Bank,New York,NY,57053,"Flagstar Bank, N.A.",12-Mar-23,10540
2,Silicon Valley Bank,Santa Clara,CA,24735,First Citizens Bank & Trust Company,10-Mar-23,10539
3,Almena State Bank,Almena,KS,15426,Equity Bank,23-Oct-20,10538
4,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb",16-Oct-20,10537

We can also **create a dataframe from a excel file** using the `.read_excel()` method or **create a dataframe from a json file** using the `.read_json()` method.

In [47]:
covid_excel = pd.read_excel("./data/Pandas1_covid_MA_06292023.xlsx")
covid_excel.head(5)

,Date,Positive Total,Positive New,Probable Total,Probable New,Estimated active cases
0,2020-06-01,97291,326,NaN,NaN,NaN
1,2020-06-02,97539,248,NaN,NaN,NaN
2,2020-06-03,97964,425,NaN,NaN,NaN
3,2020-06-04,98376,412,NaN,NaN,NaN
4,2020-06-05,98796,420,NaN,NaN,NaN

In [48]:
books_json = pd.read_json("./data/sample_books.json")
books_json.head(5)

,id,title,author,year,country,pages,available
0,1,The Digital Library,Maria Rossi,2021,Italy,210.0,True
1,2,Archives and Memory,John Smith,2019,United Kingdom,185.0,True
2,3,Text Analysis for Beginners,Anna Bianchi,2023,Italy,260.0,False
3,4,Data and Culture,Claire Dubois,2020,France,NaN,True
4,5,Introduction to Metadata,None,2022,Germany,145.0,False

Once the analysis is complete, it is possible to **write the tabular data taken from a dataframe into a file**. 

|Method|Reveals|
|---|---|
|.to_csv( )| Save a DataFrame as a CSV file |
|.to_json( )| Save a DataFrame as a JSON file|
|.to_excel( )|Save a DataFrame as an Excel file|

In [49]:
# write the dataframe we created for the world cup champions into a csv file
wcup.to_csv('./data/wcup_champions.csv')

In [50]:
# write the dataframe into a json file
covid.to_json('./data/Pandas1_covid_MA_06292023.json')

## Explore the data

After we build a dataframe, it is helpful to get a general idea of the data. The first step is to explore the dataframe's attributes. Attributes are properties of the dataframe (not functions), so they do not have parentheses `()` after them. 

|Attribute|Reveals|
|---|---|
|.shape| The number of rows and columns|
|.columns| The name of each column|


To get how many rows and columns a dataframe has, we use the `.shape` attribute. `df.shape` returns a tuple with (number of rows, number of columns).

In [39]:
# df.shape returns a tuple (# of rows, # of columns)
wcup.shape

(10, 3)

In [40]:
# Use `.columns` attribute to find the column names
wcup.columns

Index(['Year', 'Champion', 'Host'], dtype='object')

There are some methods we can use to explore the data as well. 


|Method|Reveals|
|---|---|
|.info( )| Column count and data type|
|.head( )| First five rows|
|.tail( )|Last five rows|

In [41]:
# Use `.info()` to get column count and data type
wcup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      10 non-null     int64
 1   Champion  10 non-null     object
 2   Host      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

We can get a preview of the dataframe. The `.head()` and `.tail()` methods help us do that.

In [42]:
# Display the first five rows of the data
wcup.head()

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany

In [43]:
# Display the last five rows of the data
wcup.tail()

   Year   Champion         Host
5  2002     Brazil  Korea/Japan
6  1998     France       France
7  1994     Brazil          USA
8  1990    Germany        Italy
9  1986  Argentina       Mexico

In [44]:
# Specify the number of rows at the beginning of the table to display
wcup.head(8)

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany
5  2002     Brazil   Korea/Japan
6  1998     France        France
7  1994     Brazil           USA

## Access data
In this section, we will take a look at the different ways of accessing the data in a dataframe. 

For example, instead of loading the whole dataframe, it is possible to access a column of your interest knowing its column names. You can use the bracket notation `df[ColumnName]` to get a specific column.

In [51]:
# Use bracket notation to access the column 'Champion'
wcup['Champion']

0    Argentina
1       France
2      Germany
3        Spain
4        Italy
5       Brazil
6       France
7       Brazil
8      Germany
9    Argentina
Name: Champion, dtype: object

We can also access multiple columns from a dataframe by putting the column names in a list. Note that in this case, you have two layers of hard brackets.

In [52]:
# Access multiple columns
wcup[['Year','Champion']]

   Year   Champion
0  2022  Argentina
1  2018     France
2  2014    Germany
3  2010      Spain
4  2006      Italy
5  2002     Brazil
6  1998     France
7  1994     Brazil
8  1990    Germany
9  1986  Argentina

### The indexers `.iloc` and `.loc`
In Pandas, there are two indexers `.iloc` and `.loc` that are often used to access data in a dataframe. 
#### .iloc
`.iloc` allows us to access a row or a column using its *integer location*.

Recall that in a dataframe, by default, to the left of each row are index numbers. The index numbers are similar to the index numbers for a Python list; they help us reference a particular row for data retrieval. Also, like a Python list, the index begins with 0. 

We can retrieve data using the `.iloc` attribute. The syntax of `.iloc` indexer is `df.iloc[row selection, column selection]`.

In [53]:
# Access a single row
wcup.iloc[5] # Access the row with the index number 5

Year               2002
Champion         Brazil
Host        Korea/Japan
Name: 5, dtype: object

When we select multiple consecutive rows from a dataframe, we give a starting index and an ending index. Notice that the selected rows will **not** include the final index row.

In [54]:
# Access multiple consecutive rows
wcup.iloc[2:5] # Access the rows with the index number 2, 3, and 4

   Year Champion          Host
2  2014  Germany        Brazil
3  2010    Spain  South Africa
4  2006    Italy       Germany

In [55]:
# Access multiple non-consecutive rows
wcup.iloc[[0,2,5]] # Access the rows with the index number 0, 2, and 5

   Year   Champion         Host
0  2022  Argentina        Qatar
2  2014    Germany       Brazil
5  2002     Brazil  Korea/Japan

In [56]:
# access every other row in wcup
wcup.iloc[::2]

   Year   Champion     Host
0  2022  Argentina    Qatar
2  2014    Germany   Brazil
4  2006      Italy  Germany
6  1998     France   France
8  1990    Germany    Italy

We have seen how we can access rows from a dataframe using the `.iloc` indexer. In the following, we will use the `.iloc` indexer to access columns. Recall that the syntax of `.iloc` indexer is `df.iloc[row selection, column selection]`. Again, the index numbers for the columns are similar to the index numbers for a Python list; they help us reference a particular column for data retrieval. Also, like a Python list, the index begins with 0.

In [57]:
# Access a single column
wcup.iloc[:,1] # Access the column with the index number 1

0    Argentina
1       France
2      Germany
3        Spain
4        Italy
5       Brazil
6       France
7       Brazil
8      Germany
9    Argentina
Name: Champion, dtype: object

Note that we cannot use the column name, i.e., the header, to access a column because `.iloc` accesses data using their *integer location*. If we try to access a column using its column name, we get an error!

In [58]:
# .iloc cannot access a column by its name
wcup.iloc[:,'Champion']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

We can use integer slice to access multiple columns from a dataframe.

In [ ]:
# Access multiple consecutive columns 
wcup.iloc[:,1:3] # Access the second and third column of the dataframe wcup

In [ ]:
# Access multiple non-consecutive columns
wcup.iloc[:,[0,2]] # Access the first and third column of the dataframe wcup

Now that you know how to select rows and columns from a dataframe using `.iloc`. You should be able to figure out how to get a slice of a dataframe using `.iloc`. For example, if you would like to know the champion of the world cup games between 1994 and 2010. How do you slice the dataframe `wcup` to get the part you are interested in?

In [ ]:
# Slice the dataframe using .iloc[ ]
wcup.iloc[3:8,[0,1]]

#### .loc
While `.iloc` is integer-based, `.loc` is label-based. It means that you have to access rows and columns based on their row and column labels.

The syntax of `.loc` is `df.loc[row selection, column selection]`.

At the moment, the labels for the rows are just their index numbers. When we use `.loc` to access a row, it will look very similar to what we did with `.iloc`.

In [ ]:
# Access a row using .loc
wcup.loc[0]

But we could make our index column customized. For example, we could use the column `Year` as the index column.

In [ ]:
# Set the column 'Year' as the index column
wcup = wcup.set_index('Year')
wcup

After we make the change, we will use the new labels to access the rows.

In [ ]:
# Access a row using .loc
wcup.loc[2006]

In [ ]:
# Access multiple consecutive rows
wcup.loc[2018:2010]

Note that with the label search, the ending index row is included.

In [ ]:
# Access multiple non-consecutive rows
wcup.loc[[1994, 2002, 2010]]

In [ ]:
# Access a column
wcup.loc[:, 'Host']

Now that you know how to select rows and columns from a dataframe using `.loc[ ]`. You should be able to figure out how to get a slice of a dataframe using `.loc[ ]`. For example, if you would like to know the champion of the world cup games between 1994 and 2010. How do you slice the dataframe `wcup` to get the part you are interested in?

In [ ]:
# Slice the dataframe using .loc[ ]
wcup.loc[2010:1994, ["Champion"]]

**As a quick reminder**, remember that `.iloc[]` slicing is not inclusive of the final value. On the other hand, `.loc[]` slicing does include the final value.

### The indexers `.iat` and `.at`

We have learned how to use the two indexers `.iloc` and `.loc` to access rows and columns from a dataframe. In real life, sometimes we only want to access the value in a single cell. In this case, the fastest way is to use the `.iat` and `at` indexers. We can now tell from the name that `iat` provides **integer**-based lookups while `at` provides **label**-based lookups. 

Suppose we would like to get the champion country of the 2002 world cup. How do you do that?

In [ ]:
# Get the champion country of the 2002 world cup using .at[]
wcup.at[2002, 'Champion']

In [ ]:
# Get the champion country of the 2002 world cup using .iat[]
wcup.iat[5, 0]

## Set values

Now that we know how to access data from a dataframe, we could easily use what we have learned to set the values in a dataframe. To do that, we will use assignment statements you have learned in Python Basics.

In [ ]:
# Get the data
grades = pd.read_csv('./data/Pandas1_grades.csv')
grades

### Use the indexers to set values

Recall that we have learned how to use the indexers to access a slice of a dataframe. We can use the same indexers to change the values in a dataframe. 

For example, we can get the English grades in the first two rows and change the values to 80.

In [ ]:
# Get the English grades in the first two rows and change to 80
grades.iloc[:2, 1] = 80
grades

Can you use `loc` to change the math grades in the last two rows to 90?

In [ ]:
# Change the math grades in the last two rows to 90
grades.loc[3:, "Math"] = 90
grades

And of course, we can get a single value from a dataframe and change it using `iat` or `at`.

In [ ]:
# Get Jane White's math grade and change it to 85
grades.at[3, 'Math'] = 85
grades

It's your turn. Can you get Eve Lynn's English grade and change it to 82? This time, however, use `iat`.

In [ ]:
# Get Eve Lynn's math grade and change it to 85
grades.iat[4,2] = 82
grades

### Create a new column based on an existing one

Let's get the world cup dataframe again. We add a new column Score to store the scores of the games. Can you set the values in this column to the goals that were scored by the champion in the games?

In [ ]:
# Add a new column of score
score = ["7-5", ### put the data in a list
         "4-2", 
         "1-0", 
         "1-0", 
         "6-4", 
         "2-0", 
         "3-0", 
         "3-2", 
         "1-0", 
         "3-2"]
wcup['Score'] = score # make a new column of score
wcup

In soccer games, it is common to calculate the goals scored and goals conceded by the champion in the final.

In [ ]:
# create a new column 'Goals Scored'
wcup['Goals Scored'] = wcup['Score'].str[0]
wcup

In [ ]:
# create a new column 'Goals Conceded'
wcup['Goals Conceded'] = wcup['Score'].str[-1]
wcup

With the info on goals scored and conceded by the champion, we can create a column containing the difference between the two.

In [ ]:
# Create a new column 'Difference'
wcup['Difference'] = wcup['Goals Scored'] - wcup['Goals Conceded']

We get an error! Why? The error message gives us a hint. The minus operator is not defined for the data type str! 

Luckily, Pandas has a convenient method that allows us to convert data types.

In [ ]:
# Create a new column 'Difference'
wcup['Difference'] = wcup['Goals Scored'].astype(int) -  wcup['Goals Conceded'].astype(int)
wcup