### Credits:

<img align="left" src="https://ithaka-labs.s3.amazonaws.com/static-files/images/tdm/tdmdocs/CC_BY.png"><br />

This notebook is created by Zhuo Chen based on the notebooks created by [Nathan Kelber](http://nkelber.com), [William Mattingly](https://github.com/wjbmattingly/tap-2022-pandas) and [Melanie Walsh](https://github.com/melaniewalsh/Data-Analysis-with-Pandas) under [Creative Commons CC BY License](https://creativecommons.org/licenses/by/4.0/).<br />
For questions/comments/improvements, email zhuo.chen@ithaka.org or nathan.kelber@ithaka.org<br />

Reused and modified for internal use at Università Cattolica del Sacro Cuore di Milano, by Deborah Grbac, email deborah.grbac@unicatt.it and Valentina Schiariti, email valentina.schiariti-collaboratore@unicatt.it, released under CC BY License.

This repository is founded on **Constellate notebooks**. The original Jupyter notebooks repository was designed by the educators at **ITHAKA's Constellate project**. The project was sunset on July 1, 2025. This current repository uses and resuses Constellate notebooks as Open Educational Resources (OER), free for re-use under a Creative Commons CC BY License.
___

# Pandas Intermediate 1

**Description:** This notebook describes how to:
* Group and aggregate data
* Make pivot tables

## Group and aggregate data

In Pandas basics series, you have learned how to do data cleaning, filtering and preprocessing. The next step is to summarize the data to extract useful information. Pandas provides many methods to summarize data. In this section, we'll use the Shakespeare dataframe we have worked with in [Pandas basics 2](../Pandas-basics/pandas-basics-2.ipynb) to learn these methods.

In [2]:
import pandas as pd

In [3]:
# retrieve the metadata of the example dataset Shakespeare Quarterly, 1950-present
shakespeare_df = pd.read_csv('./data/shakespeare/f6ae29d4-3a70-36ee-d601-20a8c0311273-sampled-metadata.csv')

Pandas makes summarizing a dataframe very easy. For example, we can count how many non-null values there are in each column using the `.count()` method.

In [22]:
# Get the number of non-null values in each column
shakespeare_df.count()

id                    1500
title                 1500
isPartOf              1500
publicationYear       1500
doi                      0
docType               1500
provider              1500
datePublished         1500
issueNumber           1467
volumeNumber          1500
url                   1500
creator               1209
publisher             1500
language              1500
pageStart             1443
pageEnd               1443
placeOfPublication       0
wordCount             1500
pageCount             1500
outputFormat          1500
dtype: int64

We can also get the max value or the min value of a column using the `.max()` and `.min()` methods.

In [23]:
# Get the max value from the year column
shakespeare_df['publicationYear'].max()

np.int64(2014)

In [24]:
# Get the min value from the year column
shakespeare_df['publicationYear'].min()

np.int64(1950)

You can refer to the Pandas documentation for more methods that you can use to query the data. 

When you summarize a dataframe, a very useful method is `.describe()`. It can quickly display the statistics for any group of data it is applied to.

In [4]:
# Use the .describe() method to explore the year column
shakespeare_df['title'].describe()

count               1500
unique               789
top       Review Article
freq                 508
Name: title, dtype: object

### Groupby()

Groupby is a powerful method built into Pandas that you can use to summarize your data. Groupby splits the data into different groups on a variable of your choice.

In [5]:
# Group the data by publicationYear
shakespeare_df.groupby('publicationYear')

The `groupby()` method returns a GroupBy object which describes how the rows of the original dataset have been split by the selected variable. You can actually see how the rows of the original dataframe have been grouped using the `groups` attribute after applying `groupby()`.

In [29]:
# See how the rows have been grouped
shakespeare_df.groupby('publicationYear').groups

{1950: [147, 311, 545, 572, 582, 685, 716, 722, 966, 991, 1274, 1311, 1356], 1951: [0, 21, 104, 165, 209, 239, 327, 388, 423, 467, 474, 576, 616, 717, 831, 834, 957, 975, 1008, 1062, ...], 1952: [41, 67, 79, 190, 197, 212, 378, 460, 530, 555, 588, 718, 775, 797, 865, 931, 940, 1109, 1291, 1309, ...], 1953: [75, 140, 154, 374, 384, 420, 481, 578, 626, 788, 824, 849, 875, 914, 1039, 1044, 1067, 1086, 1180, 1237, ...], 1954: [15, 74, 136, 141, 158, 174, 301, 380, 398, 425, 466, 611, 742, 803, 888, 1000, 1185, 1348, 1362, 1378, ...], 1955: [42, 54, 105, 128, 203, 271, 276, 306, 345, 381, 475, 496, 528, 529, 599, 683, 808, 835, 897, 913, ...], 1956: [12, 22, 393, 401, 412, 459, 483, 489, 598, 608, 614, 651, 697, 736, 753, 851, 946, 952, 961, 962, ...], 1957: [108, 215, 224, 230, 330, 351, 391, 405, 605, 634, 771, 786, 866, 902, 1036, 1057, 1100, 1146, 1183, 1202, ...], 1958: [28, 29, 45, 103, 114, 120, 137, 225, 235, 237, 424, 436, 512, 515, 518, 571, 650, 715, 724, 752, ...], 1959: [57, 59, 132, 207, 253, 308, 319, 323, 454, 485, 523, 575, 593, 635, 644, 666, 711, 767, 773, 795, ...], 1960: [195, 196, 223, 250, 310, 383, 385, 386, 538, 541, 550, 556, 564, 619, 628, 629, 709, 740, 777, 829, ...], 1961: [23, 93, 121, 204, 211, 373, 480, 533, 561, 586, 612, 768, 857, 956, 1010, 1013, 1094, 1113, 1153, 1216, ...], 1962: [4, 37, 123, 138, 164, 169, 259, 261, 354, 368, 429, 471, 497, 532, 574, 600, 604, 621, 658, 743, ...], 1963: [102, 155, 200, 241, 407, 415, 505, 517, 585, 625, 639, 706, 707, 734, 747, 785, 794, 814, 828, 871, ...], 1964: [62, 63, 64, 76, 139, 213, 297, 312, 314, 359, 367, 369, 417, 437, 465, 494, 495, 546, 560, 602, ...], 1965: [24, 56, 82, 126, 131, 202, 242, 399, 461, 493, 549, 638, 689, 725, 772, 1015, 1151, 1209, 1250, 1257, ...], 1966: [11, 18, 46, 91, 106, 112, 177, 193, 315, 428, 479, 610, 618, 624, 669, 677, 720, 745, 840, 925, ...], 1967: [13, 152, 299, 320, 332, 377, 557, 584, 636, 654, 713, 733, 830, 842, 900, 911, 990, 997, 1052, 1189, ...], 1968: [50, 133, 149, 389, 448, 510, 521, 674, 687, 690, 813, 854, 864, 872, 901, 1161, 1271], 1969: [95, 134, 245, 272, 349, 404, 414, 468, 766, 855, 879, 908, 917, 1001, 1006, 1011, 1053, 1081, 1150, 1343, ...], ...}

As you can see, a dictionary is returned whose keys are the unique values in publicationYear and whose values are lists of row indexes. Each key corresponds to a list of row indexes.

You can group the data using multiple variables. For example, you may want to group the documents first by their publication year and then by the publisher.

In [31]:
# Group by multiple variables 
# Take a look at the composite keys
shakespeare_df.groupby(['publicationYear', 'publisher']).groups

{(1950, 'Folger Shakespeare Library'): [147, 311, 545, 572, 582, 685, 716, 722, 966, 991, 1274, 1311, 1356], (1951, 'Folger Shakespeare Library'): [0, 21, 104, 165, 209, 239, 327, 388, 423, 467, 474, 576, 616, 717, 831, 834, 957, 975, 1008, 1062, ...], (1952, 'Folger Shakespeare Library'): [41, 67, 79, 190, 197, 212, 378, 460, 530, 555, 588, 718, 775, 797, 865, 931, 940, 1109, 1291, 1309, ...], (1953, 'Folger Shakespeare Library'): [75, 140, 154, 374, 384, 420, 481, 578, 626, 788, 824, 849, 875, 914, 1039, 1044, 1067, 1086, 1180, 1237, ...], (1954, 'Folger Shakespeare Library'): [15, 74, 136, 141, 158, 174, 301, 380, 398, 425, 466, 611, 742, 803, 888, 1000, 1185, 1348, 1362, 1378, ...], (1955, 'Folger Shakespeare Library'): [42, 54, 105, 128, 203, 271, 276, 306, 345, 381, 475, 496, 528, 529, 599, 683, 808, 835, 897, 913, ...], (1956, 'Folger Shakespeare Library'): [12, 22, 393, 401, 412, 459, 483, 489, 598, 608, 614, 651, 697, 736, 753, 851, 946, 952, 961, 962, ...], (1957, 'Folger Shakespeare Library'): [108, 215, 224, 230, 330, 351, 391, 405, 605, 634, 771, 786, 866, 902, 1036, 1057, 1100, 1146, 1183, 1202, ...], (1958, 'Folger Shakespeare Library'): [28, 29, 45, 103, 114, 120, 137, 225, 235, 237, 424, 436, 512, 515, 518, 571, 650, 715, 724, 752, ...], (1959, 'Folger Shakespeare Library'): [57, 59, 132, 207, 253, 308, 319, 323, 454, 485, 523, 575, 593, 635, 644, 666, 711, 767, 773, 795, ...], (1960, 'Folger Shakespeare Library'): [195, 196, 223, 250, 310, 383, 385, 386, 538, 541, 550, 556, 564, 619, 628, 629, 709, 740, 777, 829, ...], (1961, 'Folger Shakespeare Library'): [23, 93, 121, 204, 211, 373, 480, 533, 561, 586, 612, 768, 857, 956, 1010, 1013, 1094, 1113, 1153, 1216, ...], (1962, 'Folger Shakespeare Library'): [4, 37, 123, 138, 164, 169, 259, 261, 354, 368, 429, 471, 497, 532, 574, 600, 604, 621, 658, 743, ...], (1963, 'Folger Shakespeare Library'): [102, 155, 200, 241, 407, 415, 505, 517, 585, 625, 639, 706, 707, 734, 747, 785, 794, 814, 828, 871, ...], (1964, 'Folger Shakespeare Library'): [62, 63, 64, 76, 139, 213, 297, 312, 314, 359, 367, 369, 417, 437, 465, 494, 495, 546, 560, 602, ...], (1965, 'Folger Shakespeare Library'): [24, 56, 82, 126, 131, 202, 242, 399, 461, 493, 549, 638, 689, 725, 772, 1015, 1151, 1209, 1250, 1257, ...], (1966, 'Folger Shakespeare Library'): [11, 18, 46, 91, 106, 112, 177, 193, 315, 428, 479, 610, 618, 624, 669, 677, 720, 745, 840, 925, ...], (1967, 'Folger Shakespeare Library'): [13, 152, 299, 320, 332, 377, 557, 584, 636, 654, 713, 733, 830, 842, 900, 911, 990, 997, 1052, 1189, ...], (1968, 'Folger Shakespeare Library'): [50, 133, 149, 389, 448, 510, 521, 674, 687, 690, 813, 854, 864, 872, 901, 1161, 1271], (1969, 'Folger Shakespeare Library'): [95, 134, 245, 272, 349, 404, 414, 468, 766, 855, 879, 908, 917, 1001, 1006, 1011, 1053, 1081, 1150, 1343, ...], ...}

If you take a look at the groups in the groupby object, you will see that essentially we have a composite key for each group. The first key, for example, is (1950, 'Folger Shakespeare Library'). The value associated with this key is a list of indexes, all of which are the rows storing the documents that were published in 1950 by Folger Shakespeare Library.

We have seen how we can group the data in a dataframe. Of course, we don't just stop at grouping data. Grouping data is just a step towards data query. After we apply the `.groupby()` method, we can actually use different Pandas methods to query the data. For example, how do we get the number of documents by publisher in each publicationYear?

In [33]:
# Create a series storing the number of documents by publisher in each year
shakespeare_df.groupby(['publicationYear', 'publisher']).size()

publicationYear  publisher
1950             Folger Shakespeare Library    13
1951             Folger Shakespeare Library    29
1952             Folger Shakespeare Library    24
1953             Folger Shakespeare Library    22
1954             Folger Shakespeare Library    22
                                               ..
2010             Folger Shakespeare Library    12
2011             Folger Shakespeare Library    12
2012             Folger Shakespeare Library    17
2013             Folger Shakespeare Library    17
2014             Folger Shakespeare Library    12
Length: 73, dtype: int64

In [34]:
# get the 20 rows at the tail to see the groups more clearly
shakespeare_df.groupby(['publicationYear', 'publisher']).size().tail(20)

publicationYear  publisher
1996             Folger Shakespeare Library    19
1997             Folger Shakespeare Library    31
1998             Folger Shakespeare Library    18
1999             Folger Shakespeare Library    18
2000             Folger Shakespeare Library    18
2001             Folger Shakespeare Library    14
2002             Folger Shakespeare Library    23
                 Oxford University Press        1
2003             Folger Shakespeare Library    17
2004             Folger Shakespeare Library    21
2005             Folger Shakespeare Library    17
2006             Folger Shakespeare Library    17
2007             Folger Shakespeare Library    12
2008             Folger Shakespeare Library    15
2009             Folger Shakespeare Library    15
2010             Folger Shakespeare Library    12
2011             Folger Shakespeare Library    12
2012             Folger Shakespeare Library    17
2013             Folger Shakespeare Library    17
2014             Folger Shakespeare Library    12
dtype: int64

### Agg() 

After we group the data in a dataframe, we can apply the `agg()` method to calculate multiple statistics per group in one calculation.

For example, let's say we would like to know the sum of the word count in all the documents from each year. To achieve this goal, we can group the data by `publicationYear`, and then aggregate the data by summing the numerical values in the column of `wordCount` for each subgroup.

In [6]:
# Get the sum of word count in docs by publication year
shakespeare_df.groupby('publicationYear').agg({'wordCount':'sum'})

                 wordCount
publicationYear
1950                 32700
1951                 60595
1952                 53965
1953                 21616
1954                 48576
...                    ...
2010                 53662
2011                 40864
2012                 72507
2013                 61077
2014                 38645

[65 rows x 1 columns]

Of course, you can choose other ways to aggregate the data in each subgroup. For example, suppose you are interested in the biggest word count by year.

In [7]:
# the biggest word count by year
shakespeare_df.groupby('publicationYear').agg({'wordCount':'max'})

                 wordCount
publicationYear
1950                  5543
1951                 15540
1952                 17785
1953                  5053
1954                 12530
...                    ...
2010                 13658
2011                 14254
2012                 15208
2013                 16186
2014                 17606

[65 rows x 1 columns]

We can apply multiple aggregating functions to a single column.

In [9]:
# apply multiple functions to a single column
shakespeare_df.groupby('publicationYear').agg({'wordCount':['sum', 'max']})

                wordCount
                      sum    max
publicationYear
1950                32700   5543
1951                60595  15540
1952                53965  17785
1953                21616   5053
1954                48576  12530
...                   ...    ...
2010                53662  13658
2011                40864  14254
2012                72507  15208
2013                61077  16186
2014                38645  17606

[65 rows x 2 columns]

We can specify multiple columns to apply a function to.

In [10]:
# apply a single function to selected columns in each subgroup
shakespeare_df.groupby('publicationYear').agg({'wordCount':'sum', 'pageCount': 'max'})

                 wordCount  pageCount
publicationYear
1950                 32700         11
1951                 60595         36
1952                 53965         36
1953                 21616         10
1954                 48576         27
...                    ...        ...
2010                 53662         30
2011                 40864         31
2012                 72507         31
2013                 61077         33
2014                 38645         34

[65 rows x 2 columns]

We can also apply multiple functions to each of the selected columns.

In [11]:
# apply multiple functions to selected columns in each subgroup
shakespeare_df.groupby('publicationYear').agg({'wordCount':['sum', 'max'], 'pageCount':['max', 'size']})

                wordCount        pageCount
                      sum    max       max size
publicationYear
1950                32700   5543        11   13
1951                60595  15540        36   29
1952                53965  17785        36   24
1953                21616   5053        10   22
1954                48576  12530        27   22
...                   ...    ...       ...  ...
2010                53662  13658        30   12
2011                40864  14254        31   12
2012                72507  15208        31   17
2013                61077  16186        33   17
2014                38645  17606        34   12

[65 rows x 4 columns]

## Make pivot tables in Pandas

Pandas has a `.pivot_table()` method that we can use to summarize data. It takes a dataframe as argument and has parameters specifying the shape of the pivot table.

In the previous section, we have used the `.groupby()` and `agg()` methods to summarize data. For example, we grouped the documents in the shakespeare dataframe by their year of publication and calculated the sum of word count in those documents. We can do the same thing using the `.pivot_table` method.

In [19]:
# Create a pivot table giving the sum of 
# word count by year
shakespeare_df.pivot_table(index='publicationYear', 
                       values='wordCount',
                      aggfunc='sum')

                 wordCount
publicationYear
1950                 32700
1951                 60595
1952                 53965
1953                 21616
1954                 48576
...                    ...
2010                 53662
2011                 40864
2012                 72507
2013                 61077
2014                 38645

[65 rows x 1 columns]

Again, when aggregating the data, you can apply a single function to multiple columns.

In [20]:
# Create a pivot table giving the max value of the wordCount 
# and pageCount column by publicationYear
shakespeare_df.pivot_table(index='publicationYear', 
                       values=['wordCount', 'pageCount'],
                      aggfunc='max')

                 pageCount  wordCount
publicationYear
1950                    11       5543
1951                    36      15540
1952                    36      17785
1953                    10       5053
1954                    27      12530
...                    ...        ...
2010                    30      13658
2011                    31      14254
2012                    31      15208
2013                    33      16186
2014                    34      17606

[65 rows x 2 columns]

You can also apply multiple functions to a single column.

In [21]:
# Create a pivot table giving the sum and the mean value of
# word count by year
shakespeare_df.pivot_table(index='publicationYear', 
                       values='wordCount',
                      aggfunc=['sum', 'mean'])

                      sum         mean
                wordCount    wordCount
publicationYear
1950                32700  2515.384615
1951                60595  2089.482759
1952                53965  2248.541667
1953                21616   982.545455
1954                48576  2208.000000
...                   ...          ...
2010                53662  4471.833333
2011                40864  3405.333333
2012                72507  4265.117647
2013                61077  3592.764706
2014                38645  3220.416667

[65 rows x 2 columns]

Or, you can apply different functions to different columns.

In [22]:
# Create a pivot table giving the sum of
# the wordCount by publicationYear
# and the max value of pageCount by publicationYear
shakespeare_df.pivot_table(index='publicationYear', 
                       values=['wordCount', 'pageCount'],
                      aggfunc={'wordCount':'sum', 'pageCount':'max'})

                 pageCount  wordCount
publicationYear
1950                    11      32700
1951                    36      60595
1952                    36      53965
1953                    10      21616
1954                    27      48576
...                    ...        ...
2010                    30      53662
2011                    31      40864
2012                    31      72507
2013                    33      61077
2014                    34      38645

[65 rows x 2 columns]